Correct the opposite logic of "force_full"
pulp/pulp pull request #3918
Opened 2019-05-10 07:10 UTC by zxiong

It doesn't make sense that "force_full" enable fast-forward, so change
the opposite logic

ref #4810
https://pulp.plan.io/issues/4810

2019-05-10 07:16 UTC, zxiong commented
Following up last comment from https://github.com/pulp/pulp/pull/3917, correct the opposite logic.

2019-05-13 09:11 UTC, ipanova commented on server/pulp/plugins/file/distributor.py
> +        if not config.get("force_full", True):
force_full flag if unspecified should be set to False.
Consider changing to:
```
if not config.get("force_full", False)
```

2019-05-13 09:12 UTC, ipanova requested changes
please address https://github.com/pulp/pulp/pull/3918/files#r283252715

2019-05-13 13:10 UTC, zxiong commented
@ipanova, could you help to review it again?

2019-05-13 13:39 UTC, ipanova approved these changes

2019-05-13 15:34 UTC, dkliban commented
ok test

2019-05-14 08:23 UTC, pep8speaks commented
Hello @zxiong! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`devel/pulp/devel/mock_distributor.py`](https://github.com/pulp/pulp/blob/87be847a487b58d5d09841b68f93cab2a762cabc/devel/pulp/devel/mock_distributor.py):

> [Line 33:53](https://github.com/pulp/pulp/blob/87be847a487b58d5d09841b68f93cab2a762cabc/devel/pulp/devel/mock_distributor.py#L33): [W601](https://duckduckgo.com/?q=pep8%20W601) .has_key() is deprecated, use 'in'
> [Line 35:45](https://github.com/pulp/pulp/blob/87be847a487b58d5d09841b68f93cab2a762cabc/devel/pulp/devel/mock_distributor.py#L35): [W601](https://duckduckgo.com/?q=pep8%20W601) .has_key() is deprecated, use 'in'

* In the file [`server/pulp/plugins/file/distributor.py`](https://github.com/pulp/pulp/blob/87be847a487b58d5d09841b68f93cab2a762cabc/server/pulp/plugins/file/distributor.py):

> [Line 201:1](https://github.com/pulp/pulp/blob/87be847a487b58d5d09841b68f93cab2a762cabc/server/pulp/plugins/file/distributor.py#L201): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-05-14 08:40 UTC, zxiong commented
The failed unit tests are caused by test data which is return from "publish_conduit.get_units(criteria=criteria)" in the method "publish_repo_fast_forward", so the mock method "get_units(criteria=None)" in "pulp/devel/mock_distributor.py" is modified to add a condition to make up test data for "publish_repo_fast_forward" when the criteria likes "{'checksum': {"$in": ["sum1",...]}})"

Previously, the method "publish_repo_fast_forward" should not be covered by existing unit tests, so adding five test cases which are referring to test cases for the method "publish_repo".

Besides that, improves "publish_repo_fast_forward" to delete symlinks that pointing files were removed, and the change also is covered by new unit tests.

2019-05-14 08:43 UTC, zxiong commented
@ipanova, @dkliban, @rohanpm, could you help to review the PR again?

2019-05-14 11:35 UTC, dkliban commented
ok test

2019-05-15 16:21 UTC, merged