Fix the issue that PULP_MANIFEST is not update correctly.
pulp/pulp pull request #3923
Opened 2019-05-22 07:32 UTC by zxiong

Fix the issue that PULP_MANIFEST is not update correctly to publish
files with iso_distributor via fast-forward when deleting a exsting
unit. Besides that, add two unit tests and improve an unit test to
check the fix.

fixes #4865

2019-05-24 03:00 UTC, zxiong commented
@ipanova, @dkliban, could you help to review the PR?

2019-05-27 17:37 UTC, goosemania commented
ok test

2019-05-27 17:38 UTC, goosemania commented
Tested. It works and also fixes https://pulp.plan.io/issues/4857

2019-05-27 17:47 UTC, goosemania requested changes
It looks good, thanks for fixing @zxiong !

Please add `fixes #4857` to your commit message, since it fixes that regression as well.

2019-05-27 17:59 UTC, goosemania approved these changes
Disregard the previous comment, I marked issues as duplicates.
Thanks for the fix!

2019-05-27 17:59 UTC, merged