Add a User-Agent header to pulp downloaders
pulp/pulp pull request #3925
Opened 2019-05-24 12:51 UTC by mdellweg

2019-05-29 14:47 UTC, dkliban approved these changes

2019-05-29 14:48 UTC, dkliban requested changes
We should probably add a release note for this.

2019-06-18 14:17 UTC, mdellweg commented
ping @dkliban

2019-06-18 15:01 UTC, dkliban approved these changes

2019-06-18 15:02 UTC, merged